version: '3'
name: cosmetics-platform

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  products-service:
    build: ./products-service
    container_name: products-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  brands-service:
    build: ./brands-service
    container_name: brands-service
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/brands_db?createDatabaseIfNotExist=true
    depends_on:
      - mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cosmetics_db
    ports:
      - "3306:3306"

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

networks:
  ms-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mongo_data:
    driver: local