spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ms

  application:
    name: gateway

  profiles:
    active: dev

  config:
    import: optional:configserver:http://config-server:8088

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
