spring:
  config:
    import: optional:configserver:http://config-server:8088
  application:
    name: brands-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: brands-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer