global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "brands-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["brands-service:8082"]

  - job_name: "products-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["products-service:8085"]

  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-service:8888"]

  - job_name: "config-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-server:8088"]
