pipeline {
    agent any

    environment {
        NEXUS_URL = 'http://localhost:8081'
        NEXUS_REPO = 'maven-releases'
        NEXUS_CRED = credentials('nexus-credentials')
    }

    stages {
        stage('Build JARs') {
            steps {
                sh 'jenkins/scripts/build_jars.sh'
            }
        }
}

}