server:
  port: 8888
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: products-service
              uri: lb://PRODUCTS-SERVICE
              predicates:
                - Path=/api/products/**
            - id: brands-service
              uri: lb://BRANDS-SERVICE
              predicates:
                - Path=/api/brands/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
        minimum-number-of-calls: 5
    instances:
      productsCircuitBreaker:
        base-config: default
      brandsCircuitBreaker:
        base-config: default