server:
  port: 8088

spring:
  profiles:
    active: secret

  config:
    import: optional:file:/home/dzaoui/microservices-project/external-config/application-secret.yml

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zaoui-Douaa/microservices-config-repository.git 

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
