spring:
  config:
    import: optional:configserver:http://config-server:8088
  application:
    name: products-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      name: product-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
